# Generated by Django 6.0.2 on 2026-02-07 13:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=255, primary_key=True, serialize=False
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=255)),
                ("model", models.CharField(default="default", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("incomplete", "Incomplete"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "previous_response_id",
                    models.CharField(blank=True, db_index=True, max_length=255, null=True),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session_id", "-created_at"], name="chat_messag_session_6514f7_idx"
                    ),
                    models.Index(
                        fields=["previous_response_id"], name="chat_messag_previou_feb5d6_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=255, primary_key=True, serialize=False
                    ),
                ),
                ("type", models.CharField(default="message", max_length=50)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                            ("developer", "Developer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("incomplete", "Incomplete"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("content", models.JSONField(default=list)),
                ("session_id", models.CharField(db_index=True, max_length=255)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "response",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="output_items",
                        to="chat_messages.response",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session_id", "-created_at"], name="chat_messag_session_a71156_idx"
                    ),
                    models.Index(
                        fields=["response", "-created_at"], name="chat_messag_respons_dddefc_idx"
                    ),
                ],
            },
        ),
    ]
