# Generated by Django 6.0.2 on 2026-02-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("assistant", "Assistant"),
                    ("system", "System"),
                    ("developer", "Developer"),
                    ("tool", "Tool"),
                ],
                max_length=20,
            ),
        ),
    ]
