# Generated by Django 6.0.2 on 2026-02-08 09:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0002_alter_message_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("client_id", models.CharField(db_index=True, max_length=255)),
                ("tool_name", models.CharField(max_length=100)),
                ("command", models.CharField(max_length=255)),
                ("allowed", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("client_id", "tool_name", "command")},
            },
        ),
    ]
