# Generated by Django 6.0.2 on 2026-02-08 12:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0003_toolpermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=255, primary_key=True, serialize=False
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=255)),
                ("call_id", models.CharField(db_index=True, max_length=255)),
                ("question_text", models.TextField()),
                ("choices", models.JSONField(default=list)),
                ("allow_user_input", models.BooleanField(default=False)),
                ("user_answer", models.TextField(blank=True, null=True)),
                (
                    "answer_type",
                    models.CharField(
                        blank=True,
                        choices=[("choice", "Choice"), ("user_input", "User Input")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "response",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="chat_messages.response",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session_id", "-created_at"], name="chat_messag_session_7443f6_idx"
                    ),
                    models.Index(fields=["call_id"], name="chat_messag_call_id_096a74_idx"),
                ],
            },
        ),
    ]
