# Generated by Django 5.2.11 on 2026-02-10 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0004_question"),
        ("chat_messages", "0004_session"),
    ]

    operations = []
