# Generated by Django 5.2.11 on 2026-02-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0006_session_title_session_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("model_id", models.CharField(max_length=255, unique=True)),
                ("provider", models.CharField(db_index=True, max_length=100)),
                ("model_name", models.CharField(db_index=True, max_length=200)),
                ("display_name", models.CharField(max_length=200)),
                (
                    "input_cost_per_mtok",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "output_cost_per_mtok",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "cache_read_cost_per_mtok",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "cache_write_cost_per_mtok",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("raw_data", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["provider", "model_name"],
            },
        ),
        migrations.AddField(
            model_name="message",
            name="input_cost",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="message",
            name="input_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="message",
            name="model",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="message",
            name="output_cost",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="message",
            name="output_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="message",
            name="total_cost",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="message",
            name="total_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="response",
            name="input_cost",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="response",
            name="output_cost",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="response",
            name="total_cost",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="session",
            name="total_cost",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="session",
            name="total_input_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="session",
            name="total_output_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="session",
            name="total_tokens",
            field=models.IntegerField(default=0),
        ),
    ]
