# Generated by Django 5.2.11 on 2026-02-13 19:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0007_add_pricing_and_usage_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuggestedQuestion",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=255, primary_key=True, serialize=False
                    ),
                ),
                ("question_text", models.TextField()),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
