# Generated by Django 5.2.11 on 2026-02-14 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat_messages", "0008_suggestedquestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionFile",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=255, primary_key=True, serialize=False
                    ),
                ),
                ("path", models.CharField(db_index=True, max_length=1024)),
                ("filename", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.CharField(default="application/octet-stream", max_length=255),
                ),
                ("size", models.BigIntegerField(default=0)),
                ("text_content", models.TextField(blank=True, null=True)),
                ("is_text", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.CharField(
                        choices=[("user", "User"), ("agent", "Agent")],
                        default="user",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="chat_messages.session",
                        to_field="session_id",
                    ),
                ),
            ],
            options={
                "ordering": ["path"],
                "unique_together": {("session", "path")},
            },
        ),
    ]
