# Generated by Django 5.2.11 on 2026-02-14 09:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodicTask",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=255, primary_key=True, serialize=False
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("recipe", models.JSONField(default=dict)),
                ("schedule", models.JSONField(default=dict)),
                ("timezone_name", models.CharField(default="Asia/Seoul", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("max_retries", models.IntegerField(default=3)),
                ("consecutive_failures", models.IntegerField(default=0)),
                ("next_run_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("total_runs", models.IntegerField(default=0)),
                ("total_successes", models.IntegerField(default=0)),
                ("total_failures", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periodic_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PeriodicTaskRun",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=255, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("attempt", models.IntegerField(default=1)),
                ("output_summary", models.TextField(blank=True, default="")),
                ("error_message", models.TextField(blank=True, default="")),
                ("files_created", models.JSONField(default=list)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                ("total_cost", models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ("iterations", models.IntegerField(default=0)),
                ("tool_calls_count", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="periodic_tasks.periodictask",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="periodictask",
            index=models.Index(
                fields=["user", "-created_at"], name="periodic_ta_user_id_6a6107_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="periodictask",
            index=models.Index(
                fields=["status", "next_run_at"], name="periodic_ta_status_0e82e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="periodictaskrun",
            index=models.Index(
                fields=["task", "-started_at"], name="periodic_ta_task_id_8fe15c_idx"
            ),
        ),
    ]
