# Generated by Django 5.2.11 on 2026-02-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("periodic_tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodictask",
            name="notify_on_success",
            field=models.BooleanField(default=True),
        ),
    ]
