# Generated by Django 5.2.11 on 2026-02-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="logincode",
            name="client",
            field=models.CharField(
                choices=[("web", "Web"), ("electron", "Electron"), ("mobile", "Mobile")],
                default="web",
                max_length=16,
            ),
        ),
    ]
